import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Header1 from './components/Header/Header1';
import Footer from './components/Footer/Footer';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main-page-area">
          <Header1 />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
