import './globals.css';

export const metadata = {
  title: 'ParentMedia',
  description: 'Generated by ParentMedia',
}

import Header1 from './components/Header/Header1';
import Footer from './components/Footer/Footer';

import ThemeClient from './components/ThemeClient';

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeClient />
        <div className="main-page-area">
          <Header1 />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
